# Prometheus 설정 파일
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'blogauto-monitor'
    environment: '{{ ENVIRONMENT }}'

# Alertmanager 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# 규칙 파일 로드
rule_files:
  - "alerts/*.yml"
  - "recording_rules/*.yml"

# 스크레이프 설정
scrape_configs:
  # BlogAuto Backend API
  - job_name: 'blogauto-backend'
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: 'blogauto-api'
          component: 'backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # BlogAuto Frontend
  - job_name: 'blogauto-frontend'
    static_configs:
      - targets: ['frontend:3000']
        labels:
          service: 'blogauto-ui'
          component: 'frontend'
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    
  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'
          component: 'postgresql'
          
  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'
          component: 'redis'
          
  # Node Exporter (시스템 메트릭)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          component: 'node'
          
  # Cadvisor (컨테이너 메트릭)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'container'
          component: 'docker'
          
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'monitoring'
          component: 'prometheus'